// Bomber = ember wretch (2026-09-11): the fifth hand-drawn horde sprite in the Slagmaw
// v2.1 idiom, generated by tools/art/horde-gen.mjs (rig) + mobgen.mjs (renderer).
// 18x18 texels at den 2 for r=4.5 (FAMILIES.horde.bombSprite), feet on the bottom
// row, 4 facings x 4 run frames in the atlasSheet layout so mobFrame() keeps working.
// Fuse (owner 2026-09-11: "the explosion animation ... is just flashing a square on
// top of its head"): bombFuseSprite is a second sheet whose 4 frames are the 0.6 s
// fuse (crouch, core swells, cracks race over the body, white-hot), picked by
// e.frameT from the fuse timer; bombFuseSpriteVolc is the same in the charred skin.
// The red square becomes a swelling ember halo under the sprite.
//   lint:    node tools/art/lint.mjs bombSprite,bombFuseSprite --inject tools/art/bomber.mjs
//   preview: node tools/art/preview.mjs bombFuseSprite --inject tools/art/bomber.mjs --out <dir>
//   land:    node tools/art/land.mjs tools/art/bomber.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its bombSprite line replaces this one).
import {sheet,skinSheet,HORDE_PAL,SKINS} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const hot=r=>r.replace(/[DML]/g,'O').replace(/H/g,'Y');            // frame 3: the body glows through
const fuseSheet=S=>{const o={};for(const d of Object.keys(S))o[d]=S[d].map((rows,i)=>i===3?rows.map(hot):rows);return o;};
const withY=p=>JSON.stringify({...p,Y:'#ffd23e'});
const volc=process.env.HORDE_VOLC_SKIN||'charred';
export default {
  __after:'bombSprite',
  bombSprite:{literal:sheetLiteral('bombSprite',sheet('bomber'),'pal('+JSON.stringify(HORDE_PAL)+')',2,'ember wretch 18x18 den 2, feet row 17; frames[dir][frame] (tools/art/bomber.mjs)')},
  bombFuseSprite:{literal:sheetLiteral('bombFuseSprite',fuseSheet(sheet('bombFuse')),'pal('+withY(HORDE_PAL)+')',2,'wretch fuse: frames[dir][k], k = fuse phase 0..3 via e.frameT (tools/art/bomber.mjs)')},
  bombFuseSpriteVolc:{literal:sheetLiteral('bombFuseSpriteVolc',fuseSheet(skinSheet('bombFuse',volc)),'pal('+withY(SKINS[volc].pal)+')',2,'wretch fuse in the '+volc+' skin (tools/art/bomber.mjs)')},
  __patches:[
    // the fuse timer drives the fuse sheet (frameT is honoured by mobFrame, see tools/art/spitter.mjs)
    [`if(e.fuse<=0){e.dead=true;explode(e.x,e.y,46,15,undefined,22*dmgScale());}`,
     `e.spr=(G.biome==='volcano'&&typeof bombFuseSpriteVolc!=='undefined')?bombFuseSpriteVolc:bombFuseSprite;e.frameT=Math.min(3,Math.floor((1-e.fuse/0.6)*4)); if(e.fuse<=0){e.dead=true;explode(e.x,e.y,46,15,undefined,22*dmgScale());}`],
    // the red square becomes a swelling ember halo under the wretch, white-hot for the last tenth
    [`if(e.type==='bomber'&&e.fuse>=0&&Math.floor(e.fuse*10)%2===0){`,`if(e.type==='bomber'&&e.fuse>=0){`],
    [`ctx.fillStyle='#ff3c3c';ctx.fillRect(x-5,y-12,10,10);`,
     `const fk=1-e.fuse/0.6,BR=46;ctx.globalAlpha=0.35;ctx.strokeStyle='#ff7a1f';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,BR,0,TAU);ctx.stroke();ctx.globalAlpha=0.16+0.3*fk;ctx.fillStyle=fk>0.85?'#fff6d6':'#ff7a1f';ctx.beginPath();ctx.arc(x,y,BR*fk,0,TAU);ctx.fill();ctx.globalAlpha=1; // wretch fuse: the disc grows to the blast radius (explode r=46), flat like the other telegraphs (tools/art/bomber.mjs)`],
  ],
};
