// Burster = slag tick (2026-09-11): the second hand-drawn volcano fauna, generated by
// tools/art/fauna-gen.mjs (rig) + mobgen.mjs (renderer). 24x24 texels at den 2 for
// r=5 (FAMILIES.fauna.bursterSprite), feet on the bottom row, 4 facings x 4 walk
// frames; bursterSwellSprite is its own sheet (gold cracks widening and whitening, k =
// frame) that the burster AI already swaps in over the 0.9 s fuse while scaling it 1..1.7.
//   lint:    node tools/art/lint.mjs bursterSprite,bursterSwellSprite --inject tools/art/burster.mjs
//   preview: node tools/art/preview.mjs bursterSprite --inject tools/art/burster.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family fauna --inject tools/art/burster.mjs
//   land:    node tools/art/land.mjs tools/art/burster.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its smasher lines replace these).
import {sheet,FAUNA_PAL} from './fauna-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const palExpr='pal('+JSON.stringify(FAUNA_PAL)+')';
export default {
  bursterSprite:{literal:sheetLiteral('bursterSprite',sheet('burster'),palExpr,2,'slag tick 24x24 den 2, feet row 23; frames[dir][frame] (tools/art/burster.mjs)')},
  bursterSwellSprite:{literal:sheetLiteral('bursterSwellSprite',sheet('bursterSwell'),palExpr,2,'slag tick swell: cracks widen and whiten, k = frame; the game scales it 1..1.7 (tools/art/burster.mjs)')},
};
