// Chaser = ghoul (2026-09-07): the first hand-drawn horde sprite in the Slagmaw v2.1
// idiom, generated by tools/art/horde-gen.mjs (rig) + mobgen.mjs (renderer).
// 20x20 texels at den 2 for r=5 (FAMILIES.horde.chaserSprite), feet on the bottom
// row, 4 facings x 4 walk frames in the atlasSheet layout so mobFrame() keeps working.
//   lint:    node tools/art/lint.mjs chaserSprite --inject tools/art/chaser.mjs
//   preview: node tools/art/preview.mjs chaserSprite --inject tools/art/chaser.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family horde --inject tools/art/chaser.mjs
//   frame:   node tools/frame.mjs out.png --inject tools/art/chaser.mjs --wave 1
//   land:    node tools/art/land.mjs tools/art/chaser.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its chaserSprite line replaces this one).
import {sheet,HORDE_PAL} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const S=sheet('chaser');
export default {
  chaserSprite:{literal:sheetLiteral('chaserSprite',S,'pal('+JSON.stringify(HORDE_PAL)+')',2,'ghoul 20x20 den 2, feet row 19; frames[dir][frame] (tools/art/chaser.mjs)')},
};
