// Fireslug = lava slug (2026-09-11): the third hand-drawn volcano fauna, generated by
// tools/art/fauna-gen.mjs (rig) + mobgen.mjs (renderer). 32x24 texels at den 2 for
// r=6 (FAMILIES.fauna.fireslugSprite), feet on the bottom row, 4 facings x 4 crawl
// frames in the atlasSheet layout so mobFrame() keeps working; the game drips lava
// behind it (lavaDrip) so the sprite only has to look molten underneath.
//   lint:    node tools/art/lint.mjs fireslugSprite --inject tools/art/fireslug.mjs
//   preview: node tools/art/preview.mjs fireslugSprite --inject tools/art/fireslug.mjs --out <dir>
//   land:    node tools/art/land.mjs tools/art/fireslug.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its fireslugSprite line replaces this one).
import {sheet,FAUNA_PAL} from './fauna-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';
export default {
  fireslugSprite:{literal:sheetLiteral('fireslugSprite',sheet('fireslug'),'pal('+JSON.stringify(FAUNA_PAL)+')',2,'lava slug 32x24 den 2, feet row 23; frames[dir][frame] (tools/art/fireslug.mjs)')},
};
