// Ghost = wraith (2026-09-12): the mob of THE CRYSTAL MAZE, generated by
// tools/art/horde-gen.mjs (rig `wraith`) + mobgen.mjs. 20x22 texels at den 2 for
// r=5 (FAMILIES.horde.ghostSprite); no feet — the robe tapers into wisps and the
// four frames hover and sway instead of stepping. The game draws it at 70% alpha
// with a violet glow and lets it drift through crystal and rock (e.ghost).
//   lint:    node tools/art/lint.mjs ghostSprite --inject tools/art/ghost.mjs
//   preview: node tools/art/preview.mjs ghostSprite --inject tools/art/ghost.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family horde --inject tools/art/ghost.mjs
//   land:    node tools/art/land.mjs tools/art/ghost.mjs && cd tools && npm run gates
import {sheet,HORDE_PAL} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const S=sheet('ghost');
export default {
  __after:'bombSprite',
  ghostSprite:{literal:sheetLiteral('ghostSprite',S,'pal('+JSON.stringify(HORDE_PAL)+')',2,'wraith 20x22 den 2, hover frames; frames[dir][frame] (tools/art/ghost.mjs)')},
};
