// Smasher = slag brute (2026-09-11): the first hand-drawn volcano fauna, generated by
// tools/art/fauna-gen.mjs (rig) + mobgen.mjs (renderer). 28x28 texels at den 2 for
// r=6.5 (FAMILIES.fauna.smasherSprite), feet on the bottom row, 4 facings x 4 walk
// frames; smasherCastSprite is its own sheet (fists overhead, seams flaring) that the
// smasher AI already swaps in for the Molten Slam wind-up.
//   lint:    node tools/art/lint.mjs smasherSprite,smasherCastSprite --inject tools/art/smasher.mjs
//   preview: node tools/art/preview.mjs smasherSprite --inject tools/art/smasher.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family fauna --inject tools/art/smasher.mjs
//   land:    node tools/art/land.mjs tools/art/smasher.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its smasher lines replace these).
import {sheet,FAUNA_PAL} from './fauna-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const palExpr='pal('+JSON.stringify(FAUNA_PAL)+')';
export default {
  smasherSprite:{literal:sheetLiteral('smasherSprite',sheet('smasher'),palExpr,2,'slag brute 28x28 den 2, feet row 27; frames[dir][frame] (tools/art/smasher.mjs)')},
  smasherCastSprite:{literal:sheetLiteral('smasherCastSprite',sheet('smasherCast'),palExpr,2,'slag brute cast: fists overhead, seams flare on frames 2-3 (tools/art/smasher.mjs)')},
};
