// Spitter = bile toad (2026-09-11): the third hand-drawn horde sprite in the Slagmaw
// v2.1 idiom, generated by tools/art/horde-gen.mjs (rig) + mobgen.mjs (renderer).
// 20x20 texels at den 2 for r=5 (FAMILIES.horde.spitSprite), feet on the bottom
// row, 4 facings x 4 HOP frames (sit, launch, air, land) in the atlasSheet layout.
// Two game patches make it hop for real: the spitter AI moves in bursts on the
// launch/air frames and lifts the sprite with e.hopY (the enemy draw already casts
// a ground shadow when hopY>1), and mobFrame() honours e.frameT so a toad that has
// stopped to spit sits on frame 0 instead of kicking in place.
//   lint:    node tools/art/lint.mjs spitSprite --inject tools/art/spitter.mjs
//   preview: node tools/art/preview.mjs spitSprite --inject tools/art/spitter.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family horde --inject tools/art/spitter.mjs
//   frame:   node tools/frame.mjs out.png --inject tools/art/spitter.mjs --wave 6
//   land:    node tools/art/land.mjs tools/art/spitter.mjs && cd tools && npm run gates
// Roll back the art by landing tools/art/ninja.mjs again (its spitSprite line replaces
// this one); the two patches below stay harmless with any sheet.
import {sheet,HORDE_PAL} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const S=sheet('spitter');
export default {
  spitSprite:{literal:sheetLiteral('spitSprite',S,'pal('+JSON.stringify(HORDE_PAL)+')',2,'bile toad 20x20 den 2, feet row 19; hop frames sit/launch/air/land (tools/art/spitter.mjs)')},
  __patches:[ // single-line anchors: playground.html is LF and pixboot.rep() CRLF-normalises multi-line needles
    [`else if(dd<160)sp=0;`,
     `else if(dd<160)sp=0; { /* bile toad hop (tools/art/spitter.mjs): move in bursts on the sheet's launch/air frames (1,2), lifted by hopY (casts the ground shadow); sit on frame 0 while still */ const ph=((G.time*7+(e.id||0))%4+4)%4,air=ph>=1&&ph<3; if(sp!==0){sp=air?sp*2:0;e.hopY=air?6*Math.sin(Math.PI*(ph-1)/2):0;e.frameT=undefined;}else{e.hopY=0;e.frameT=0;} }`],
    [`return sheetFrame(e.spr,e._fx||0,e._fy===undefined?1:e._fy,G.time*7+(e.id||0));}`,
     `return sheetFrame(e.spr,e._fx||0,e._fy===undefined?1:e._fy,e.frameT!==undefined?e.frameT:G.time*7+(e.id||0));}`],
  ],
};
