// Swarm = skitter (2026-09-11): the second hand-drawn horde sprite in the Slagmaw
// v2.1 idiom, generated by tools/art/horde-gen.mjs (rig) + mobgen.mjs (renderer).
// 16x12 texels at den 2 for r=3.5 (FAMILIES.horde.swarmSprite), feet on the bottom
// row, 4 facings x 4 walk frames in the atlasSheet layout so mobFrame() keeps working.
//   lint:    node tools/art/lint.mjs swarmSprite --inject tools/art/swarm.mjs
//   preview: node tools/art/preview.mjs swarmSprite --inject tools/art/swarm.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family horde --inject tools/art/chaser.mjs,tools/art/swarm.mjs
//   frame:   node tools/frame.mjs out.png --inject tools/art/swarm.mjs --wave 3
//   land:    node tools/art/land.mjs tools/art/swarm.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its swarmSprite line replaces this one).
import {sheet,HORDE_PAL} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const S=sheet('swarm');
export default {
  swarmSprite:{literal:sheetLiteral('swarmSprite',S,'pal('+JSON.stringify(HORDE_PAL)+')',2,'skitter 16x12 den 2, feet row 11; frames[dir][frame] (tools/art/swarm.mjs)')},
};
