// Tank = grave hulk (2026-09-11): the fourth hand-drawn horde sprite in the Slagmaw
// v2.1 idiom, generated by tools/art/horde-gen.mjs (rig) + mobgen.mjs (renderer).
// 36x36 texels at den 2 for r=9 (FAMILIES.horde.tankSprite), feet on the bottom
// row, 4 facings x 4 walk frames in the atlasSheet layout so mobFrame() keeps working.
//   lint:    node tools/art/lint.mjs tankSprite --inject tools/art/tank.mjs
//   preview: node tools/art/preview.mjs tankSprite --inject tools/art/tank.mjs --out <dir>
//   sheet:   node tools/sheet.mjs sprites --family horde --inject tools/art/tank.mjs
//   frame:   node tools/frame.mjs out.png --inject tools/art/tank.mjs --wave 6
//   land:    node tools/art/land.mjs tools/art/tank.mjs && cd tools && npm run gates
// Roll back by landing tools/art/ninja.mjs again (its tankSprite line replaces this one).
import {sheet,HORDE_PAL} from './horde-gen.mjs';
import {sheetLiteral} from './mobgen.mjs';

const S=sheet('tank');
export default {
  tankSprite:{literal:sheetLiteral('tankSprite',S,'pal('+JSON.stringify(HORDE_PAL)+')',2,'grave hulk 36x36 den 2, feet row 35; frames[dir][frame] (tools/art/tank.mjs)')},
};
